protocol: 'https:'
host: 'b.ueda.tech'
sitetitle: '上田ブログ'
subtitle: 'なお、このサイトはbashでできている。'
headline:
- text: '<a href="https://amzn.to/2PY7TcB">詳解確率ロボティクス出版されました</a>'
- text: '<a href="/?page=bashcms2">シェルスクリプト高速開発手法入門改訂2版発売中</a>'
- text: '<a href="https://employment.en-japan.com/engineerhub/entry/2019/02/19/103000">エンジニアHubで記事を書きました</a>'
twitter:
- account: 'ryuichiueda'
facebook: '@'
hatena: '@'
pocket: '@'
line: '@'
links:
- text: 'latest'
  href: '/?post'
- text: 'publications'
  href: '/?page=00728'
  sublinks:
  - text: 'Publication List (English)'
    href: '/?page=publication_en'
  - text: '出版物リスト（書籍・商業誌等）'
    href: '/?page=06030'
  - text: '出版物リスト（学術誌等）'
    href: '/?page=06033'
  - text: '書籍の情報'
    href: '/?page=05535'
  - text: '- 詳解確率ロボティクス'
    href: '/?page=lnpr'
  - text: '- シェルスクリプト高速開発手法入門 改訂2版'
    href: '/?page=bashcms2'
  - text: '- Raspberry Piで学ぶ ROSロボット入門'
    href: '/?page=09461'
  - text: '- シェルプログラミング実用テクニック'
    href: '/?page=05787'
  - text: '- シェルスクリプト高速開発手法入門 初版'
    href: '/?page=03344'
  - text: '- 確率ロボティクス'
    href: '/?page=01441'
  - text: '雑誌連載記事の情報'
    href: '/?page=02939'
  - text: '- シェル芸人からの挑戦状'
    href: '/?page=gihyo_shellgei_series'
  - text: '- Raspberry Piで作ろう お手軽ロボット教室 | 日経Linux'
    href: '/?page=07166'
  - text: '- Raspberry Piで始めるかんたんロボット製作 | 日経Linux'
    href: '/?page=05983'
  - text: '- Haskellでやってはいかんのか？ | USP Magazine'
    href: '/?page=02944'
  - text: '- 開眼シェルスクリプト | SoftwareDesign'
    href: '/?page=02949'
  - text: '著作物の購入'
    href: '/?page=mybookstore'
- text: 'projects'
  sublinks:
  - text: 'シェル芸'
    href: '/?page=01434'
  - text: 'opy（ワンライナー用Python）'
    href: '/?page=opy'
  - text: 'GlueLang'
    href: '/?page=GlueLang'
  - text: '研究 <i class="fa fa-external-link"></i>'
    href: 'https://lab.ueda.tech/?page_id=60'
- text: 'records'
  href: './'
  sublinks:
  - text: '受賞等'
    href: '/?page=00823'
  - text: '学会等の活動記録'
    href: '/?page=01746'
  - text: '外部獲得資金'
    href: '/?page=02317'
- text: 'misc'
  href: '/?page=01242'
  sublinks:
  - text: '資料室'
    href: '/?page=07879'
  - text: '- Tera TermをWindowsにインストールしてからssh接続するまで'
    href: '/?page=10067'
  - text: '- Tera Termで鍵を作って鍵認証でサーバにログインするまで'
    href: '/?page=10088'
  - text: '- AnacondaをWindowsにインストールする手順'
    href: '/?page=anaconda_windows'
  - text: 'dashのコード解読メモ'
    href: '/?page=04219'
  - text: '- dash/src/main.h, main.c'
    href: '/?page=04223'
  - text: '- dash/src/shell.h'
    href: '/?page=04276'
  - text: '- dash/src/eval.h, eval.c'
    href: '/?page=04346'
  - text: 'おはようございますの世紀'
    href: '/?page=01980'
  - text: '研究関係動画'
    href: '/?page=09712'
  - text: '- 某PFoEの改良（アルゴリズム未発表）'
    href: '/?page=10021'
  - text: '- 某PFCの改良（アルゴリズム未発表）'
    href: '/?page=10034'
  - text: 'イベント等の動画'
    href: '/?page=09692'
  - text: '動画 | Raspberry Pi Mouse + ROS'
    href: '/?page=09663'
  - text: 'ARAIBOムービーまとめ'
    href: '/?page=00851'
  - text: 'シェル芸勉強会の動画'
    href: '/?page=09678'
- text: 'links'
  href: '/?page=00811'
  sublinks:
  - text: '千葉工大上田研究室'
    href: 'https://lab.ueda.tech/'
  - text: 'USP友の会'
    href: 'http://www.usptomo.com'
  - text: 'Team ARAIBO'
    href: 'http://www.araibo.com'
  - text: 'ARAIBOムービーまとめ'
    href: '/?page=00851'
sociallinks:
- icon: 'fa-wikipedia-w'
  href: 'https://ja.wikipedia.org/wiki/%E4%B8%8A%E7%94%B0%E9%9A%86%E4%B8%80'
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/ryuichiueda'
- icon: 'fa-github-square'
  href: 'https://github.com/ryuichiueda'
- icon: 'fa-slideshare'
  href: 'https://www.slideshare.net/ryuichiueda'
- icon: 'fa-facebook-squar'
  href: 'https://www.facebook.com/%E4%B8%8A%E7%94%B0-%E9%9A%86%E4%B8%80-675930229170437/'
- icon: 'fa-linkedin-square'
  href: 'https://www.linkedin.com/in/%E9%9A%86%E4%B8%80-%E4%B8%8A%E7%94%B0-81391649'
- icon: 'fa-instagram'
  href: 'https://www.instagram.com/ryuichiueda/'
- icon: 'fa-graduation-cap'
  href: 'https://www.researchgate.net/profile/Ryuichi_Ueda'
- icon: 'fa-question'
  href: 'https://peing.net/ja/ryuichiueda'
